import type { QuizQuestion } from "./types";

export const FALLBACK_QUESTIONS: QuizQuestion[] = [
  // FACILE (Levels 1-5)
  {
    id: "fallback-f1",
    question: "Quelle est la capitale de la France ?",
    answer: "Paris",
    badAnswers: ["Lyon", "Marseille", "Bordeaux"],
    category: "Geographie",
    difficulty: "facile",
  },
  {
    id: "fallback-f2",
    question: "Combien de jours y a-t-il dans une année non bissextile ?",
    answer: "365",
    badAnswers: ["364", "366", "360"],
    category: "Culture générale",
    difficulty: "facile",
  },
  {
    id: "fallback-f3",
    question: "Quel animal est le symbole de la république française ?",
    answer: "Le coq",
    badAnswers: ["L'aigle", "Le lion", "Le cheval"],
    category: "Histoire",
    difficulty: "facile",
  },
  {
    id: "fallback-f4",
    question: "Quel est le plus grand océan de la planète ?",
    answer: "L'océan Pacifique",
    badAnswers: ["L'océan Atlantique", "L'océan Indien", "L'océan Arctique"],
    category: "Geographie",
    difficulty: "facile",
  },
  {
    id: "fallback-f5",
    question: "Quel célèbre peintre a peint la Joconde ?",
    answer: "Léonard de Vinci",
    badAnswers: ["Pablo Picasso", "Claude Monet", "Vincent van Gogh"],
    category: "Art",
    difficulty: "facile",
  },
  {
    id: "fallback-f6",
    question: "Combien de couleurs compose un arc-en-ciel traditionnel ?",
    answer: "7",
    badAnswers: ["5", "6", "8"],
    category: "Science",
    difficulty: "facile",
  },
  {
    id: "fallback-f7",
    question: "Quel est le métal précieux jaune associé à l'or ?",
    answer: "L'Or",
    badAnswers: ["L'Argent", "Le Bronze", "Le Cuivre"],
    category: "Science",
    difficulty: "facile",
  },
  {
    id: "fallback-f8",
    question: "Dans quel pays se trouvent les pyramides de Gizeh ?",
    answer: "Égypte",
    badAnswers: ["Grèce", "Mexique", "Japon"],
    category: "Histoire",
    difficulty: "facile",
  },

  // NORMAL (Levels 6-10)
  {
    id: "fallback-n1",
    question: "En quelle année l'homme a-t-il marché sur la Lune pour la première fois ?",
    answer: "1969",
    badAnswers: ["1965", "1972", "1961"],
    category: "Histoire",
    difficulty: "normal",
  },
  {
    id: "fallback-n2",
    question: "Quel est l'élément le plus abondant dans l'atmosphère terrestre ?",
    answer: "L'Azote",
    badAnswers: ["L'Oxygène", "Le Carbone", "L'Hydrogène"],
    category: "Science",
    difficulty: "normal",
  },
  {
    id: "fallback-n3",
    question: "Qui a écrit la pièce de théâtre 'Ruy Blas' ?",
    answer: "Victor Hugo",
    badAnswers: ["Molière", "Jean Racine", "Émile Zola"],
    category: "Litterature",
    difficulty: "normal",
  },
  {
    id: "fallback-n4",
    question: "Quelle planète du système solaire est surnommée la planète rouge ?",
    answer: "Mars",
    badAnswers: ["Jupiter", "Vénus", "Saturne"],
    category: "Science",
    difficulty: "normal",
  },
  {
    id: "fallback-n5",
    question: "En quelle année a eu lieu la Révolution française ?",
    answer: "1789",
    badAnswers: ["1776", "1815", "1799"],
    category: "Histoire",
    difficulty: "normal",
  },
  {
    id: "fallback-n6",
    question: "Quel fleuve traverse la ville de Rome ?",
    answer: "Le Tibre",
    badAnswers: ["Le Pô", "L'Arno", "Le Rhône"],
    category: "Geographie",
    difficulty: "normal",
  },

  // DIFFICILE (Levels 11-15)
  {
    id: "fallback-d1",
    question: "Quel scientifique a formulé le principe d'incertitude en physique quantique ?",
    answer: "Werner Heisenberg",
    badAnswers: ["Albert Einstein", "Niels Bohr", "Erwin Schrödinger"],
    category: "Science",
    difficulty: "difficile",
  },
  {
    id: "fallback-d2",
    question: "Quel traité a mis fin à la guerre de Cent Ans en 1453 ?",
    answer: "Le traité de Picquigny",
    badAnswers: ["Le traité de Troyes", "Le traité de Verdun", "Le traité d'Utrecht"],
    category: "Histoire",
    difficulty: "difficile",
  },
  {
    id: "fallback-d3",
    question: "Combien d'os possède un corps humain adulte ?",
    answer: "206",
    badAnswers: ["198", "214", "250"],
    category: "Biologie",
    difficulty: "difficile",
  },
  {
    id: "fallback-d4",
    question: "Quel est le plus haut sommet du continent africain ?",
    answer: "Le Kilimandjaro",
    badAnswers: ["Le Mont Kenya", "Le Mont Toubkal", "Le Ruwenzori"],
    category: "Geographie",
    difficulty: "difficile",
  },
  {
    id: "fallback-d5",
    question: "Dans quelle ville a été inventée la première montre à quartz ?",
    answer: "Neuchâtel",
    badAnswers: ["Genève", "Tokyo", "Zurich"],
    category: "Inventions",
    difficulty: "difficile",
  },
];
