import type { QuizQuestion } from "./types";

export const FALLBACK_QUESTIONS: QuizQuestion[] = [
  // ==================== FACILE (Levels 1-5) ====================
  {
    id: "fallback-f1",
    question: "Quelle est la capitale de la France ?",
    answer: "Paris",
    badAnswers: ["Lyon", "Marseille", "Bordeaux"],
    category: "Geographie",
    difficulty: "facile",
  },
  {
    id: "fallback-f2",
    question: "Combien de jours y a-t-il dans une année non bissextile ?",
    answer: "365",
    badAnswers: ["364", "366", "360"],
    category: "Culture générale",
    difficulty: "facile",
  },
  {
    id: "fallback-f3",
    question: "Quel animal est le symbole national de la République française ?",
    answer: "Le coq",
    badAnswers: ["L'aigle", "Le lion", "Le cheval"],
    category: "Histoire",
    difficulty: "facile",
  },
  {
    id: "fallback-f4",
    question: "Quel est le plus grand océan de la planète Terre ?",
    answer: "L'océan Pacifique",
    badAnswers: ["L'océan Atlantique", "L'océan Indien", "L'océan Arctique"],
    category: "Geographie",
    difficulty: "facile",
  },
  {
    id: "fallback-f5",
    question: "Quel célèbre peintre de la Renaissance a peint la Joconde ?",
    answer: "Léonard de Vinci",
    badAnswers: ["Pablo Picasso", "Claude Monet", "Vincent van Gogh"],
    category: "Art",
    difficulty: "facile",
  },
  {
    id: "fallback-f6",
    question: "Combien de couleurs composent un arc-en-ciel traditionnel ?",
    answer: "7",
    badAnswers: ["5", "6", "8"],
    category: "Science",
    difficulty: "facile",
  },
  {
    id: "fallback-f7",
    question: "Quel élément chimique a pour symbole 'Au' ?",
    answer: "L'Or",
    badAnswers: ["L'Argent", "Le Cuivre", "L'Aluminium"],
    category: "Science",
    difficulty: "facile",
  },
  {
    id: "fallback-f8",
    question: "Dans quel sport illustre s'est distingué le champion Zinedine Zidane ?",
    answer: "Football",
    badAnswers: ["Tennis", "Basket-ball", "Rugby"],
    category: "Sport",
    difficulty: "facile",
  },
  {
    id: "fallback-f9",
    question: "Quel célèbre plombier moustachu est l'emblème de la société Nintendo ?",
    answer: "Mario",
    badAnswers: ["Luigi", "Sonic", "Link"],
    category: "Jeux vidéos",
    difficulty: "facile",
  },
  {
    id: "fallback-f10",
    question: "Dans quel pays européen se situe la célèbre tour de Pise ?",
    answer: "Italie",
    badAnswers: ["Espagne", "Grèce", "Portugal"],
    category: "Geographie",
    difficulty: "facile",
  },
  {
    id: "fallback-f11",
    question: "Quel est l'organe principal du système circulatoire humain ?",
    answer: "Le cœur",
    badAnswers: ["Le poumon", "Le foie", "Le cerveau"],
    category: "Science",
    difficulty: "facile",
  },
  {
    id: "fallback-f12",
    question: "Quel personnage porte un chapeau rouge et adore le fromage dans la BD d'Astérix ?",
    answer: "Obélix",
    badAnswers: ["Tintin", "Gaston Lagaffe", "Lucky Luke"],
    category: "Culture générale",
    difficulty: "facile",
  },
  {
    id: "fallback-f13",
    question: "Quelle spécialité culinaire napolitaine est garnie de sauce tomate et mozzarella ?",
    answer: "La pizza",
    badAnswers: ["La paëlla", "Le couscous", "La moussaka"],
    category: "Gastronomie",
    difficulty: "facile",
  },
  {
    id: "fallback-f14",
    question: "Quel groupe britannique a chanté les succès 'Yellow Submarine' et 'Hey Jude' ?",
    answer: "The Beatles",
    badAnswers: ["The Rolling Stones", "Queen", "Pink Floyd"],
    category: "Musique",
    difficulty: "facile",
  },
  {
    id: "fallback-f15",
    question: "Combien de côtés possède un hexagone régulier ?",
    answer: "6",
    badAnswers: ["5", "7", "8"],
    category: "Science",
    difficulty: "facile",
  },

  // ==================== NORMAL (Levels 6-10) ====================
  {
    id: "fallback-n1",
    question: "En quelle année a eu lieu la Révolution française (Prise de la Bastille) ?",
    answer: "1789",
    badAnswers: ["1715", "1804", "1848"],
    category: "Histoire",
    difficulty: "normal",
  },
  {
    id: "fallback-n2",
    question: "Quel est le plus long fleuve qui traverse la France métropolitaine ?",
    answer: "La Loire",
    badAnswers: ["La Seine", "Le Rhône", "La Garonne"],
    category: "Geographie",
    difficulty: "normal",
  },
  {
    id: "fallback-n3",
    question: "Qui a écrit la tragédie classique 'Roméo et Juliette' ?",
    answer: "William Shakespeare",
    badAnswers: ["Victor Hugo", "Molière", "Voltaire"],
    category: "Arts et littérature",
    difficulty: "normal",
  },
  {
    id: "fallback-n4",
    question: "Quel est l'astre le plus proche de la planète Terre ?",
    answer: "La Lune",
    badAnswers: ["Mars", "Vénus", "Le Soleil"],
    category: "Science",
    difficulty: "normal",
  },
  {
    id: "fallback-n5",
    question: "Dans quel film réalisé par James Cameron entend-on 'My Heart Will Go On' ?",
    answer: "Titanic",
    badAnswers: ["Avatar", "Gladiator", "Inception"],
    category: "TV et cinéma",
    difficulty: "normal",
  },
  {
    id: "fallback-n6",
    question: "Quel pays d'Afrique a pour capitale la ville de Dakar ?",
    answer: "Le Sénégal",
    badAnswers: ["Le Mali", "La Côte d'Ivoire", "Le Cameroun"],
    category: "Geographie",
    difficulty: "normal",
  },
  {
    id: "fallback-n7",
    question: "Quel compositeur autrichien a créé l'opéra 'La Flûte enchantée' ?",
    answer: "Wolfgang Amadeus Mozart",
    badAnswers: ["Ludwig van Beethoven", "Johann Sebastian Bach", "Frédéric Chopin"],
    category: "Musique",
    difficulty: "normal",
  },
  {
    id: "fallback-n8",
    question: "En quelle année le Mur de Berlin a-t-il été détruit ?",
    answer: "1989",
    badAnswers: ["1985", "1991", "1979"],
    category: "Histoire",
    difficulty: "normal",
  },
  {
    id: "fallback-n9",
    question: "Combien de joueurs composent une équipe de handball sur le terrain ?",
    answer: "7",
    badAnswers: ["6", "8", "11"],
    category: "Sport",
    difficulty: "normal",
  },
  {
    id: "fallback-n10",
    question: "Dans le jeu 'The Legend of Zelda', quel est le nom du héros au bonnet vert ?",
    answer: "Link",
    badAnswers: ["Zelda", "Ganon", "Epona"],
    category: "Jeux vidéos",
    difficulty: "normal",
  },
  {
    id: "fallback-n11",
    question: "Quel célèbre saucisson sec alsacien ou lorrain est parfumé à l'ail ?",
    answer: "Le Cervelas",
    badAnswers: ["La Rosette", "Le Chorizo", "La Mortadelle"],
    category: "Gastronomie",
    difficulty: "normal",
  },
  {
    id: "fallback-n12",
    question: "Qui a sculpté la statue en bronze 'Le Penseur' ?",
    answer: "Auguste Rodin",
    badAnswers: ["Camille Claudel", "Edgar Degas", "Michel-Ange"],
    category: "Arts et littérature",
    difficulty: "normal",
  },

  // ==================== DIFFICILE (Levels 11-15) ====================
  {
    id: "fallback-d1",
    question: "En quelle année l'homme a-t-il marché sur la Lune pour la première fois (Apollo 11) ?",
    answer: "1969",
    badAnswers: ["1961", "1965", "1972"],
    category: "Histoire",
    difficulty: "difficile",
  },
  {
    id: "fallback-d2",
    question: "Quel physicien a formulé la théorie de la relativité restreinte en 1905 ?",
    answer: "Albert Einstein",
    badAnswers: ["Isaac Newton", "Niels Bohr", "Galilée"],
    category: "Science",
    difficulty: "difficile",
  },
  {
    id: "fallback-d3",
    question: "Quelle est la capitale administrative et politique de l'Australie ?",
    answer: "Canberra",
    badAnswers: ["Sydney", "Melbourne", "Brisbane"],
    category: "Geographie",
    difficulty: "difficile",
  },
  {
    id: "fallback-d4",
    question: "Qui a écrit le célèbre roman épique 'Les Misérables' paru en 1862 ?",
    answer: "Victor Hugo",
    badAnswers: ["Émile Zola", "Gustave Flaubert", "Honoré de Balzac"],
    category: "Arts et littérature",
    difficulty: "difficile",
  },
  {
    id: "fallback-d5",
    question: "Quel est l'élément le plus abondant dans l'atmosphère terrestre ?",
    answer: "L'Azote (N2)",
    badAnswers: ["L'Oxygène (O2)", "Le Dioxyde de carbone (CO2)", "L'Argon (Ar)"],
    category: "Science",
    difficulty: "difficile",
  },
  {
    id: "fallback-d6",
    question: "En quel siècle s'est déroulée la guerre de Cent Ans entre la France et l'Angleterre ?",
    answer: "XIVe - XVe siècle",
    badAnswers: ["XIIe - XIIIe siècle", "XVIe - XVIIe siècle", "Xe - XIe siècle"],
    category: "Histoire",
    difficulty: "difficile",
  },
  {
    id: "fallback-d7",
    question: "Quel philosophe grec ancien fut le maître d'Alexandre le Grand ?",
    answer: "Aristote",
    badAnswers: ["Socrate", "Platon", "Pythagore"],
    category: "Histoire",
    difficulty: "difficile",
  },
  {
    id: "fallback-d8",
    question: "Quel pays détient le plus grand nombre de titres en Coupe du monde de football ?",
    answer: "Le Brésil",
    badAnswers: ["L'Allemagne", "L'Italie", "L'Argentine"],
    category: "Sport",
    difficulty: "difficile",
  },
  {
    id: "fallback-d9",
    question: "Dans quelle ville italienne se situe la célèbre galerie des Offices ?",
    answer: "Florence",
    badAnswers: ["Rome", "Venise", "Milan"],
    category: "Art",
    difficulty: "difficile",
  },
  {
    id: "fallback-d10",
    question: "Quel était le véritable nom de scène de la chanteuse Edith Piaf à ses débuts ?",
    answer: "La Môme Piaf",
    badAnswers: ["La Môme Moineau", "L'Aigle Noir", "La Rose"],
    category: "Musique",
    difficulty: "difficile",
  },
];
